# Generated by Django 3.1.2 on 2021-01-20 23:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0005_delete_place_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='txt_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myFile', models.FileField(upload_to='files')),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime(2021, 1, 20, 15, 15, 42, 185799))),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
