# Generated by Django 3.1.2 on 2021-01-21 05:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0006_txt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txt_file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 21, 45, 24, 488444)),
        ),
        migrations.CreateModel(
            name='recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='recordings')),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime(2021, 1, 20, 21, 45, 24, 488444))),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(default=datetime.datetime(2021, 1, 20, 21, 45, 24, 488444))),
                ('checked_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_by', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
