# Generated by Django 3.1.2 on 2021-01-21 05:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0007_auto_20210120_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='checked_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 21, 50, 31, 930027)),
        ),
        migrations.AlterField(
            model_name='recording',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 21, 50, 31, 930027)),
        ),
        migrations.AlterField(
            model_name='txt_file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 21, 50, 31, 930027)),
        ),
        migrations.CreateModel(
            name='initial_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=datetime.datetime(2021, 1, 20, 21, 50, 31, 931028))),
                ('ratings', models.IntegerField()),
                ('feedback', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('new_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_user', to=settings.AUTH_USER_MODEL)),
                ('recordings', models.ManyToManyField(to='application.recording')),
            ],
        ),
    ]
