# Generated by Django 3.1.2 on 2021-01-21 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20210120_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initial_test',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initial_test',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 22, 36, 3, 83345)),
        ),
        migrations.AlterField(
            model_name='recording',
            name='checked_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 22, 36, 3, 83345)),
        ),
        migrations.AlterField(
            model_name='recording',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 22, 36, 3, 83345)),
        ),
        migrations.AlterField(
            model_name='txt_file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 22, 36, 3, 83345)),
        ),
    ]
