# Generated by Django 3.1.2 on 2021-01-23 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210120_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='sentence',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='initial_test',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 16, 39, 22, 774992)),
        ),
        migrations.AlterField(
            model_name='recording',
            name='checked_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 16, 39, 22, 773991)),
        ),
        migrations.AlterField(
            model_name='recording',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 16, 39, 22, 773991)),
        ),
        migrations.AlterField(
            model_name='txt_file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 16, 39, 22, 772990)),
        ),
    ]
